services:
  maestro-app:
    build:
      context: ./Maetro-MVP
      dockerfile: Dockerfile
    image: maestro-app
    devices:
      - "/dev/snd:/dev/snd"  # Donne accès direct aux périphériques audio
    group_add:
      - audio
    volumes:
      - /run/user/${UID:-1000}/pulse/native:/tmp/pulse_socket
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
    environment:
      - PULSE_SERVER=unix:/tmp/pulse_socket
      - PULSE_COOKIE=/root/.config/pulse/cookie
      - AZURE_VISION_ENDPOINT=${AZURE_VISION_ENDPOINT}
      - AZURE_VISION_KEY=${AZURE_VISION_KEY}
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - MISTRAL_API_KEY
      - CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - MAESTRO_VISUAL_URL=http://visual-service:5000/api/frame
    ports:
      - "8080:8080"
    networks:
      - maestro-net
    depends_on:
      ollama-model-puller:
        condition: service_completed_successfully

  visual-service:
    container_name: visual-service
    build:
      context: ./visual-service
      dockerfile: Dockerfile
    image: visual-service
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      maestro-app:
        condition: service_started
    networks:
      - maestro-net
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - PYTHONUNBUFFERED=1
      - JAVA_BACKEND_URL=http://host.docker.internal:8080/api/trigger
    restart: unless-stopped
    logging:
      driver: "none"

  webapp:
    build:
      context: ./maestro-front
      dockerfile: Dockerfile
      args:
        - VITE_VIDEO_URL=http://localhost:5000/video_feed
        - VITE_USER_PROFILE_URL=http://localhost:8080/api/profile
    image: maestro-front
    ports:
      - "3000:80"
    depends_on:
      - visual-service
    logging:
      driver: "none"

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - maestro-net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 120s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    logging:
      driver: "none"

  # --- Service d'initialisation (télécharge Moondream) ---
  ollama-model-puller:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - maestro-net
    entrypoint: /bin/sh
    command: ["-c", "ollama pull moondream:v2 "]
    logging:
      driver: "none"

volumes:
  ollama_data:

networks:
  maestro-net:
    driver: bridge
