services:
  maestro-app:
    build:
      context: ./Maetro-MVP
      dockerfile: Dockerfile
    image: maestro-app
    devices:
      - "/dev/snd:/dev/snd"  # Donne accès direct aux périphériques audio
    group_add:
      - audio
    environment:
      - AZURE_VISION_ENDPOINT=${AZURE_VISION_ENDPOINT}
      - AZURE_VISION_KEY=${AZURE_VISION_KEY}
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - MISTRAL_API_KEY
      - CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      ollama-model-puller:
        condition: service_completed_successfully

  visual-service:
    build:
      context: ./visual-service
      dockerfile: Dockerfile
    image: visual-service
    ports:
      - "5000:5000"
    depends_on:
      maestro-app:
        condition: service_started

    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    logging:
      driver: "none"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: maestro-webapp
    ports:
      - "80:80"
    depends_on:
      - visual-service
    logging:
      driver: "none"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 120s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    logging:
      driver: "none"

  # --- Service d'initialisation (télécharge Moondream) ---
  ollama-model-puller:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: /bin/sh
    command: ["-c", "ollama pull moondream:v2 "]
    logging:
      driver: "none"

volumes:
  ollama_data:
